{ ============================================================================
  DeepSpec.Services.Render

  HTML rendering service. Generates static HTML from .deepspec data
  for human review in WebView2 (P2) or external browser (P1).
  ============================================================================ }

unit DeepSpec.Services.Render;

interface

uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  DeepSpec.Services.Scan,
  DeepSpec.Models;

type
  TDeepSpecRenderService = class(TInterfacedObject)
  private
    FBasePath: string;
    function HtmlEscape(const S: string): string;
    function PageHeader(const ATitle: string): string;
    function PageFooter: string;
    function StatusBadge(const AStatus: string): string;
    function ConfidenceBadge(const AConf: string): string;
    function SourceLayerBadge(const ALayer: string): string;
  public
    procedure Initialize(const ADeepSpecPath: string);
    procedure RenderScanReport(AScan: TDeepSpecScanService;
      const AProjectName, AProjectType: string);
    procedure RenderIndex(const AProjectName: string; ATotalFiles: Integer);
    procedure RenderTree(const ATreeName, ATreeTitle: string;
      ANodes: System.Generics.Collections.TList<DeepSpec.Models.TSpecNode>);
    procedure RenderProblemsPage(
      AFuncNodes, AModuleNodes, AViewNodes, ADataNodes: TList<TSpecNode>);
    procedure RenderBundlesPage(
      ABundles: TList<TSemanticBundle>;
      AFuncNodes, AModuleNodes, AViewNodes, ADataNodes: TList<TSpecNode>);
  end;

implementation

uses
  System.IOUtils,
  System.DateUtils,
  System.StrUtils;

procedure TDeepSpecRenderService.Initialize(const ADeepSpecPath: string);
begin
  FBasePath := TPath.Combine(ADeepSpecPath, 'html');
  if not TDirectory.Exists(FBasePath) then
    TDirectory.CreateDirectory(FBasePath);
end;

function TDeepSpecRenderService.HtmlEscape(const S: string): string;
begin
  Result := S
    .Replace('&', '&amp;')
    .Replace('<', '&lt;')
    .Replace('>', '&gt;')
    .Replace('"', '&quot;');
end;

function TDeepSpecRenderService.PageHeader(const ATitle: string): string;
begin
  Result :=
    '<!DOCTYPE html>' + sLineBreak +
    '<html lang="en">' + sLineBreak +
    '<head>' + sLineBreak +
    '  <meta charset="UTF-8">' + sLineBreak +
    '  <title>' + HtmlEscape(ATitle) + ' - DeepSpec</title>' + sLineBreak +
    '  <style>' + sLineBreak +
    '    body { font-family: -apple-system, "Segoe UI", sans-serif; margin: 2em; color: #333; }' + sLineBreak +
    '    h1 { border-bottom: 2px solid #4a90e2; padding-bottom: 0.5em; }' + sLineBreak +
    '    h2 { color: #4a90e2; margin-top: 1.5em; }' + sLineBreak +
    '    .stat { display: inline-block; margin: 0.5em 1em 0.5em 0; padding: 0.5em 1em;' + sLineBreak +
    '            background: #f0f4f8; border-left: 3px solid #4a90e2; }' + sLineBreak +
    '    .stat strong { display: block; font-size: 1.5em; color: #4a90e2; }' + sLineBreak +
    '    .file-list { background: #f9f9f9; padding: 1em; border-radius: 4px; max-height: 400px; overflow-y: auto; }' + sLineBreak +
    '    .file-list code { display: block; padding: 0.2em 0; font-size: 0.9em; }' + sLineBreak +
    '    .badge { display: inline-block; padding: 0.2em 0.6em; border-radius: 3px;' + sLineBreak +
    '             font-size: 0.85em; margin-right: 0.5em; }' + sLineBreak +
    '    .badge-doc { background: #e3f2fd; color: #1976d2; }' + sLineBreak +
    '    .badge-code { background: #f3e5f5; color: #7b1fa2; }' + sLineBreak +
    '    .badge-ui { background: #fff3e0; color: #f57c00; }' + sLineBreak +
    '    .badge-config { background: #e8f5e9; color: #388e3c; }' + sLineBreak +
    '    .badge-ai { background: #fce4ec; color: #c2185b; }' + sLineBreak +
    '    footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #eee;' + sLineBreak +
    '             color: #999; font-size: 0.85em; }' + sLineBreak +
    '  </style>' + sLineBreak +
    '</head>' + sLineBreak +
    '<body>' + sLineBreak;
end;

function TDeepSpecRenderService.PageFooter: string;
begin
  Result :=
    '<footer>' + sLineBreak +
    '  Generated by DeepSpec at ' +
    HtmlEscape(FormatDateTime('yyyy-mm-dd hh:nn:ss', Now)) + sLineBreak +
    '</footer>' + sLineBreak +
    '</body>' + sLineBreak +
    '</html>' + sLineBreak;
end;

procedure TDeepSpecRenderService.RenderScanReport(AScan: TDeepSpecScanService;
  const AProjectName, AProjectType: string);
var
  LSb: TStringBuilder;

  procedure AppendCategory(const ATitle, ABadgeClass: string;
    AFiles: TArray<string>);
  begin
    LSb.AppendLine('<h2><span class="badge ' + ABadgeClass + '">' +
      HtmlEscape(ATitle) + '</span> ' + Length(AFiles).ToString + '</h2>');
    if Length(AFiles) = 0 then
      LSb.AppendLine('<p><em>No files in this category.</em></p>')
    else
    begin
      LSb.AppendLine('<div class="file-list">');
      for var LFile in AFiles do
        LSb.AppendLine('<code>' + HtmlEscape(LFile) + '</code>');
      LSb.AppendLine('</div>');
    end;
  end;

begin
  LSb := TStringBuilder.Create;
  try
    LSb.Append(PageHeader('Scan Report'));

    LSb.AppendLine('<h1>Scan Report: ' + HtmlEscape(AProjectName) + '</h1>');
    LSb.AppendLine('<p>Project type: <strong>' + HtmlEscape(AProjectType) + '</strong></p>');

    LSb.AppendLine('<h2>Summary</h2>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.TotalFiles.ToString + '</strong>Total files</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcDocuments).ToString + '</strong>Documents</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcCode).ToString + '</strong>Code</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcUI).ToString + '</strong>UI</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcConfig).ToString + '</strong>Config</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcAiRules).ToString + '</strong>AI Rules</div>');

    AppendCategory('Documents', 'badge-doc', AScan.GetFilesByCategory(fcDocuments));
    AppendCategory('Code', 'badge-code', AScan.GetFilesByCategory(fcCode));
    AppendCategory('UI', 'badge-ui', AScan.GetFilesByCategory(fcUI));
    AppendCategory('Config', 'badge-config', AScan.GetFilesByCategory(fcConfig));
    AppendCategory('AI Rules', 'badge-ai', AScan.GetFilesByCategory(fcAiRules));

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'scan-report.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
  end;
end;

procedure TDeepSpecRenderService.RenderIndex(const AProjectName: string;
  ATotalFiles: Integer);
var
  LSb: TStringBuilder;
begin
  LSb := TStringBuilder.Create;
  try
    LSb.Append(PageHeader('Index'));
    LSb.AppendLine('<h1>DeepSpec: ' + HtmlEscape(AProjectName) + '</h1>');
    LSb.AppendLine('<p>Welcome to your project specification.</p>');
    LSb.AppendLine('<h2>Pages</h2>');
    LSb.AppendLine('<ul>');
    LSb.AppendLine('  <li><a href="scan-report.html">Scan Report</a> (' +
      ATotalFiles.ToString + ' files)</li>');
    LSb.AppendLine('  <li><a href="problems.html">Problems</a></li>');
    LSb.AppendLine('  <li><a href="bundles.html">Bundles</a></li>');
    LSb.AppendLine('  <li><a href="function-tree.html">Function Tree</a></li>');
    LSb.AppendLine('  <li><a href="module-tree.html">Module Tree</a></li>');
    LSb.AppendLine('  <li><a href="view-tree.html">View Tree</a></li>');
    LSb.AppendLine('  <li><a href="data-tree.html">Data Tree</a></li>');
    LSb.AppendLine('</ul>');
    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'index.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
  end;
end;

function TDeepSpecRenderService.StatusBadge(const AStatus: string): string;
begin
  Result := '<span class="badge badge-' + AStatus + '">' +
    HtmlEscape(AStatus) + '</span>';
end;

function TDeepSpecRenderService.ConfidenceBadge(const AConf: string): string;
begin
  Result := '<span class="badge badge-conf-' + AConf + '">' +
    HtmlEscape(AConf) + '</span>';
end;

function TDeepSpecRenderService.SourceLayerBadge(const ALayer: string): string;
begin
  Result := '<span class="badge badge-source">' + HtmlEscape(ALayer) + '</span>';
end;

procedure TDeepSpecRenderService.RenderTree(const ATreeName, ATreeTitle: string;
  ANodes: System.Generics.Collections.TList<DeepSpec.Models.TSpecNode>);
var
  LSb: TStringBuilder;
  LNodeMap: TDictionary<string, DeepSpec.Models.TSpecNode>;

  procedure RenderNode(const ANodeId: string; ADepth: Integer);
  begin
    var LNode: DeepSpec.Models.TSpecNode;
    if not LNodeMap.TryGetValue(ANodeId, LNode) then Exit;

    var LStatus := DeepSpec.Models.TSpecEnums.NodeStatusToStr(LNode.Status);

    LSb.AppendLine('<li class="node node-depth-' + ADepth.ToString + '" data-node-id="' +
      HtmlEscape(LNode.Id) + '">');
    LSb.Append('<div class="node-header">');
    LSb.Append('<span class="node-title">' + HtmlEscape(LNode.Title) + '</span> ');
    LSb.Append('<span class="node-kind">' + HtmlEscape(LNode.Kind) + '</span> ');
    LSb.Append(StatusBadge(LStatus));
    LSb.Append(' <span class="badge badge-gen-' +
      DeepSpec.Models.TSpecEnums.GenStatusToStr(LNode.GenStatus) + '">gen:' +
      HtmlEscape(DeepSpec.Models.TSpecEnums.GenStatusToStr(LNode.GenStatus)) + '</span>');
    LSb.Append(' <span class="badge badge-review-' +
      DeepSpec.Models.TSpecEnums.ReviewStatusToStr(LNode.ReviewStatus) + '">rev:' +
      HtmlEscape(DeepSpec.Models.TSpecEnums.ReviewStatusToStr(LNode.ReviewStatus)) + '</span>');
    LSb.Append(' ');
    LSb.Append(ConfidenceBadge(DeepSpec.Models.TSpecEnums.ConfidenceToStr(LNode.Confidence)));
    LSb.Append(' ');
    LSb.Append(SourceLayerBadge(DeepSpec.Models.TSpecEnums.SourceLayerToStr(LNode.SourceLayer)));

    // Decision buttons for candidate nodes (JS Bridge writes back via WebView2 postMessage)
    if LStatus = 'candidate' then
    begin
      LSb.Append(' <span class="decision-toolbar">');
      LSb.Append('<button class="btn-confirm" data-action="node-confirm" data-node-id="' +
        HtmlEscape(LNode.Id) + '" data-node-title="' + HtmlEscape(LNode.Title) +
        '" title="Confirm this node">'#$2713' Confirm</button>');
      LSb.Append('<button class="btn-reject" data-action="node-reject" data-node-id="' +
        HtmlEscape(LNode.Id) + '" data-node-title="' + HtmlEscape(LNode.Title) +
        '" title="Reject this node">'#$2715' Reject</button>');
      LSb.Append('</span>');
    end;

    LSb.AppendLine('</div>');

    if LNode.Summary <> '' then
      LSb.AppendLine('<div class="node-summary">' + HtmlEscape(LNode.Summary) + '</div>');

    // Data-tree specific badges
    if LNode.Tree = ttData then
    begin
      if LNode.DataType <> '' then
        LSb.AppendLine('<div class="node-data-type"><span class="badge badge-data-type">' +
          HtmlEscape(LNode.DataType) + '</span></div>');
      if LNode.HasRiskScore then
        LSb.AppendLine('<div class="node-risk"><span class="badge badge-risk-' +
          DeepSpec.Models.TSpecEnums.RiskLevelToStr(LNode.RiskScore) + '">' +
          'risk: ' + HtmlEscape(DeepSpec.Models.TSpecEnums.RiskLevelToStr(LNode.RiskScore)) +
          '</span></div>');
      if LNode.Persistence <> '' then
        LSb.AppendLine('<div class="node-persistence"><span class="badge badge-persistence">' +
          HtmlEscape(LNode.Persistence) + '</span></div>');
    end;

    if Length(LNode.AcceptanceCriteria) > 0 then
    begin
      LSb.AppendLine('<details class="node-criteria"><summary>Acceptance Criteria</summary><ul>');
      for var LCrit in LNode.AcceptanceCriteria do
        LSb.AppendLine('<li>' + HtmlEscape(LCrit) + '</li>');
      LSb.AppendLine('</ul></details>');
    end;

    // Trust signals (collapsible)
    if (Length(LNode.SourceRefs) > 0) or (Length(LNode.DecisionRefs) > 0) or
      (Length(LNode.RelatedFunctions) > 0) or (Length(LNode.RelatedModules) > 0) or
      (Length(LNode.RelatedViews) > 0) or (Length(LNode.RelatedData) > 0) then
    begin
      LSb.AppendLine('<details class="trust-signals"><summary>Trust Signals</summary>');
      LSb.AppendLine('<div class="trust-signal-body">');

      // Evidence sources
      if Length(LNode.SourceRefs) > 0 then
      begin
        LSb.AppendLine('<div class="trust-section"><strong>Evidence:</strong>');
        for var LRef in LNode.SourceRefs do
        begin
          LSb.Append('<span class="trust-item trust-ref">');
          LSb.Append(HtmlEscape(LRef.RefId));
          if LRef.Relevance <> '' then
            LSb.Append(' <span class="trust-relevance">' + HtmlEscape(LRef.Relevance) + '</span>');
          LSb.AppendLine('</span>');
        end;
        LSb.AppendLine('</div>');
      end;

      // Cross-tree references
      var LHasCross := False;
      if Length(LNode.RelatedFunctions) > 0 then begin LHasCross := True;
        LSb.AppendLine('<div class="trust-section"><strong>Functions:</strong>');
        for var LRef in LNode.RelatedFunctions do
          LSb.Append('<span class="trust-item trust-func">' + HtmlEscape(LRef) + '</span>');
        LSb.AppendLine('</div>');
      end;
      if Length(LNode.RelatedModules) > 0 then begin
        LSb.AppendLine('<div class="trust-section"><strong>Modules:</strong>');
        for var LRef in LNode.RelatedModules do
          LSb.Append('<span class="trust-item trust-mod">' + HtmlEscape(LRef) + '</span>');
        LSb.AppendLine('</div>');
      end;
      if Length(LNode.RelatedViews) > 0 then begin
        LSb.AppendLine('<div class="trust-section"><strong>Views:</strong>');
        for var LRef in LNode.RelatedViews do
          LSb.Append('<span class="trust-item trust-view">' + HtmlEscape(LRef) + '</span>');
        LSb.AppendLine('</div>');
      end;
      if Length(LNode.RelatedData) > 0 then begin
        LSb.AppendLine('<div class="trust-section"><strong>Data:</strong>');
        for var LRef in LNode.RelatedData do
          LSb.Append('<span class="trust-item trust-data">' + HtmlEscape(LRef) + '</span>');
        LSb.AppendLine('</div>');
      end;

      // Decision history
      if Length(LNode.DecisionRefs) > 0 then
      begin
        LSb.AppendLine('<div class="trust-section"><strong>Decisions:</strong>');
        for var LRef in LNode.DecisionRefs do
          LSb.Append('<span class="trust-item trust-dec">' + HtmlEscape(LRef) + '</span>');
        LSb.AppendLine('</div>');
      end;

      LSb.AppendLine('</div></details>');
    end;

    if Length(LNode.Children) > 0 then
    begin
      LSb.AppendLine('<ul class="node-children">');
      for var LChildId in LNode.Children do
        RenderNode(LChildId, ADepth + 1);
      LSb.AppendLine('</ul>');
    end;

    LSb.AppendLine('</li>');
  end;

begin
  LSb := TStringBuilder.Create;
  LNodeMap := TDictionary<string, DeepSpec.Models.TSpecNode>.Create;
  try
    for var LNode in ANodes do
      LNodeMap.AddOrSetValue(LNode.Id, LNode);

    LSb.Append(PageHeader(ATreeTitle));

    // Tree-specific styles
    LSb.AppendLine('<style>');
    LSb.AppendLine('  .node { list-style: none; margin: 0.5em 0; }');
    LSb.AppendLine('  .node-header { padding: 0.4em; border-radius: 4px;');
    LSb.AppendLine('                 background: #f8f9fa; cursor: pointer; }');
    LSb.AppendLine('  .node-header:hover { background: #e9ecef; }');
    LSb.AppendLine('  .node-title { font-weight: 600; }');
    LSb.AppendLine('  .node-kind { color: #6c757d; font-size: 0.9em; font-style: italic; }');
    LSb.AppendLine('  .node-summary { padding: 0.3em 0.4em; color: #495057; font-size: 0.95em; }');
    LSb.AppendLine('  .node-children { padding-left: 1.5em; border-left: 2px solid #dee2e6; }');
    LSb.AppendLine('  .badge-candidate { background: #fff3cd; color: #856404; }');
    LSb.AppendLine('  .badge-confirmed { background: #d4edda; color: #155724; }');
    LSb.AppendLine('  .badge-uncertain { background: #f8d7da; color: #721c24; }');
    LSb.AppendLine('  .badge-rejected { background: #d6d8db; color: #383d41; }');
    LSb.AppendLine('  .badge-superseded { background: #d6d8db; color: #383d41; }');
    LSb.AppendLine('  .badge-conf-low { background: #f8d7da; color: #721c24; }');
    LSb.AppendLine('  .badge-conf-medium { background: #fff3cd; color: #856404; }');
    LSb.AppendLine('  .badge-conf-high { background: #d4edda; color: #155724; }');
    LSb.AppendLine('  .badge-source { background: #cce5ff; color: #004085; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-gen-draft { background: #e2e3e5; color: #383d41; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-gen-generated { background: #cce5ff; color: #004085; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-gen-confirmed { background: #d4edda; color: #155724; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-gen-skipped { background: #d6d8db; color: #6c757d; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-review-unreviewed { background: #e2e3e5; color: #383d41; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-review-accepted { background: #d4edda; color: #155724; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-review-rejected { background: #f8d7da; color: #721c24; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-review-deferred { background: #fff3cd; color: #856404; font-size: 0.75em; }');
    LSb.AppendLine('  .badge-data-type { background: #e2d9f3; color: #4a2d8a; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-risk-low { background: #d4edda; color: #155724; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-risk-medium { background: #fff3cd; color: #856404; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-risk-high { background: #f8d7da; color: #721c24; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-risk-critical { background: #721c24; color: #fff; font-size: 0.8em; }');
    LSb.AppendLine('  .badge-persistence { background: #d1ecf1; color: #0c5460; font-size: 0.8em; }');
    LSb.AppendLine('  details summary { cursor: pointer; color: #4a90e2; padding: 0.3em 0.4em; }');
    LSb.AppendLine('  .decision-toolbar { margin-left: 0.5em; }');
    LSb.AppendLine('  .decision-toolbar button { font-size: 0.8em; margin-left: 0.25em;');
    LSb.AppendLine('    padding: 0.15em 0.5em; border: 1px solid #ced4da; border-radius: 3px;');
    LSb.AppendLine('    background: #fff; cursor: pointer; }');
    LSb.AppendLine('  .decision-toolbar .btn-confirm { color: #155724; border-color: #c3e6cb; }');
    LSb.AppendLine('  .decision-toolbar .btn-confirm:hover { background: #d4edda; }');
    LSb.AppendLine('  .decision-toolbar .btn-reject { color: #721c24; border-color: #f5c6cb; }');
    LSb.AppendLine('  .decision-toolbar .btn-reject:hover { background: #f8d7da; }');
    LSb.AppendLine('  .decision-toolbar button.posted { opacity: 0.5; cursor: default; }');
    LSb.AppendLine('  .trust-signals summary { cursor: pointer; color: #6c757d; font-size: 0.85em;');
    LSb.AppendLine('    padding: 0.2em 0.4em; border-top: 1px solid #dee2e6; margin-top: 0.3em; }');
    LSb.AppendLine('  .trust-signal-body { padding: 0.4em; font-size: 0.9em; }');
    LSb.AppendLine('  .trust-section { margin: 0.3em 0; }');
    LSb.AppendLine('  .trust-section strong { color: #495057; font-size: 0.85em; }');
    LSb.AppendLine('  .trust-item { display: inline-block; margin: 0.1em 0.3em;');
    LSb.AppendLine('    padding: 0.1em 0.4em; border-radius: 3px; font-size: 0.85em; }');
    LSb.AppendLine('  .trust-ref { background: #d1ecf1; color: #0c5460; }');
    LSb.AppendLine('  .trust-func { background: #d4edda; color: #155724; }');
    LSb.AppendLine('  .trust-mod { background: #cce5ff; color: #004085; }');
    LSb.AppendLine('  .trust-view { background: #fff3cd; color: #856404; }');
    LSb.AppendLine('  .trust-data { background: #e2d9f3; color: #4a2d8a; }');
    LSb.AppendLine('  .trust-dec { background: #f5d0e8; color: #8b4572; }');
    LSb.AppendLine('  .trust-relevance { color: #6c757d; font-size: 0.9em; }');
    LSb.AppendLine('</style>');

    LSb.AppendLine('<h1>' + HtmlEscape(ATreeTitle) + '</h1>');
    LSb.AppendLine('<p><a href="index.html">'#$2190' Back to index</a></p>');

    if ANodes.Count = 0 then
      LSb.AppendLine('<p><em>This tree is empty. Run LLM generation to populate.</em></p>')
    else
    begin
      LSb.AppendLine('<ul class="tree-root" style="padding-left: 0;">');
      // Render roots first (no parent_id)
      for var LRoot in ANodes do
        if LRoot.ParentId = '' then
          RenderNode(LRoot.Id, 0);
      LSb.AppendLine('</ul>');
    end;

    // JS Bridge: forward decision-button clicks to the WebView2 host.
    // Falls back to a no-op (with visible warning) when opened in a regular browser.
    LSb.AppendLine('<script>');
    LSb.AppendLine('(function() {');
    LSb.AppendLine('  var hasBridge = !!(window.chrome && window.chrome.webview && window.chrome.webview.postMessage);');
    LSb.AppendLine('  document.addEventListener("click", function(e) {');
    LSb.AppendLine('    var t = e.target;');
    LSb.AppendLine('    if (!(t instanceof HTMLElement)) return;');
    LSb.AppendLine('    var action = t.getAttribute("data-action");');
    LSb.AppendLine('    if (!action) return;');
    LSb.AppendLine('    if (t.classList.contains("posted")) return;');
    LSb.AppendLine('    var msg = {');
    LSb.AppendLine('      action: action,');
    LSb.AppendLine('      node_id: t.getAttribute("data-node-id") || "",');
    LSb.AppendLine('      node_title: t.getAttribute("data-node-title") || ""');
    LSb.AppendLine('    };');
    LSb.AppendLine('    if (hasBridge) {');
    LSb.AppendLine('      try { window.chrome.webview.postMessage(JSON.stringify(msg)); }');
    LSb.AppendLine('      catch (err) { console.error("DeepSpec bridge:", err); return; }');
    LSb.AppendLine('      t.classList.add("posted");');
    LSb.AppendLine('      t.textContent = (action === "node-confirm" ? "'#$2713' posted" : "'#$2715' posted");');
    LSb.AppendLine('    } else {');
    LSb.AppendLine('      alert("DeepSpec bridge unavailable. Open this page inside DeepSpec to record decisions.");');
    LSb.AppendLine('    }');
    LSb.AppendLine('  });');
    LSb.AppendLine('})();');
    LSb.AppendLine('</script>');

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, ATreeName + '.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
    LNodeMap.Free;
  end;
end;

procedure TDeepSpecRenderService.RenderProblemsPage(
  AFuncNodes, AModuleNodes, AViewNodes, ADataNodes: TList<TSpecNode>);
var
  LSb: TStringBuilder;
  LAllIds: TDictionary<string, Boolean>;

  procedure ScanNodes(const ATreeLabel: string; ANodes: TList<TSpecNode>);
  begin
    if ANodes = nil then Exit;
    for var LNode in ANodes do
    begin
      // Low confidence
      if LNode.Confidence = clLow then
        LSb.AppendLine('<li class="problem problem-low-confidence">' +
          '<span class="badge badge-conf-low">low confidence</span> ' +
          HtmlEscape(LNode.Title) +
          ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span>' +
          ' <code>' + HtmlEscape(LNode.Id) + '</code>' +
          '</li>');

      // No evidence (no source_refs and not generated/confirmed)
      if (Length(LNode.SourceRefs) = 0)
        and (LNode.GenStatus in [gsDraft, gsGenerated])
        and (LNode.SourceLayer = slAiInferred) then
        LSb.AppendLine('<li class="problem problem-no-evidence">' +
          '<span class="badge badge-prob-no-evidence">no evidence</span> ' +
          HtmlEscape(LNode.Title) +
          ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span>' +
          ' <code>' + HtmlEscape(LNode.Id) + '</code>' +
          '</li>');

      // Candidate/unreviewed node (needs human review)
      if (LNode.Status = nsCandidate) and (LNode.ReviewStatus = rsUnreviewed) then
        LSb.AppendLine('<li class="problem problem-unreviewed">' +
          '<span class="badge badge-prob-unreviewed">unreviewed</span> ' +
          HtmlEscape(LNode.Title) +
          ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span>' +
          ' <code>' + HtmlEscape(LNode.Id) + '</code>' +
          '</li>');

      // Uncertain node
      if LNode.Status = nsUncertain then
        LSb.AppendLine('<li class="problem problem-uncertain">' +
          '<span class="badge badge-uncertain">uncertain</span> ' +
          HtmlEscape(LNode.Title) +
          ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span>' +
          ' <code>' + HtmlEscape(LNode.Id) + '</code>' +
          '</li>');

      // Orphan: has parent_id but parent not found in any tree
      if LNode.ParentId <> '' then
      begin
        var LFound := False;
        for var LN in AFuncNodes do
          if LN.Id = LNode.ParentId then begin LFound := True; Break; end;
        if not LFound then
          for var LN in AModuleNodes do
            if LN.Id = LNode.ParentId then begin LFound := True; Break; end;
        if not LFound then
          for var LN in AViewNodes do
            if LN.Id = LNode.ParentId then begin LFound := True; Break; end;
        if not LFound then
          for var LN in ADataNodes do
            if LN.Id = LNode.ParentId then begin LFound := True; Break; end;
        if not LFound then
          LSb.AppendLine('<li class="problem problem-orphan">' +
            '<span class="badge badge-prob-orphan">orphan</span> ' +
            HtmlEscape(LNode.Title) +
            ' — parent <code>' + HtmlEscape(LNode.ParentId) + '</code> not found' +
            ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span>' +
            '</li>');
      end;
    end;
  end;

  procedure CheckNodeRefs(const ATreeLabel: string; ANodes: TList<TSpecNode>);
  begin
    if ANodes = nil then Exit;
    for var LN in ANodes do
    begin
      for var LRef in LN.RelatedFunctions do
        if (LAllIds <> nil) and not LAllIds.ContainsKey(LRef) then
          LSb.AppendLine('<li class="problem problem-orphan">' +
            '<span class="badge badge-prob-orphan">broken ref</span> ' +
            HtmlEscape(LN.Title) + ' '#8594' func <code>' + HtmlEscape(LRef) + '</code> (not found)' +
            ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span></li>');
      for var LRef in LN.RelatedModules do
        if (LAllIds <> nil) and not LAllIds.ContainsKey(LRef) then
          LSb.AppendLine('<li class="problem problem-orphan">' +
            '<span class="badge badge-prob-orphan">broken ref</span> ' +
            HtmlEscape(LN.Title) + ' '#8594' mod <code>' + HtmlEscape(LRef) + '</code> (not found)' +
            ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span></li>');
      for var LRef in LN.RelatedViews do
        if (LAllIds <> nil) and not LAllIds.ContainsKey(LRef) then
          LSb.AppendLine('<li class="problem problem-orphan">' +
            '<span class="badge badge-prob-orphan">broken ref</span> ' +
            HtmlEscape(LN.Title) + ' '#8594' view <code>' + HtmlEscape(LRef) + '</code> (not found)' +
            ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span></li>');
      for var LRef in LN.RelatedData do
        if (LAllIds <> nil) and not LAllIds.ContainsKey(LRef) then
          LSb.AppendLine('<li class="problem problem-orphan">' +
            '<span class="badge badge-prob-orphan">broken ref</span> ' +
            HtmlEscape(LN.Title) + ' '#8594' data <code>' + HtmlEscape(LRef) + '</code> (not found)' +
            ' <span class="problem-tree">(' + HtmlEscape(ATreeLabel) + ')</span></li>');
    end;
  end;

begin
  LSb := TStringBuilder.Create;
  LAllIds := nil;
  try
    LSb.Append(PageHeader('Problems'));

    LSb.AppendLine('<style>');
    LSb.AppendLine('  .problem { list-style: none; padding: 0.4em 0.6em; margin: 0.3em 0;' +
      ' border-radius: 4px; border-left: 3px solid #dc3545; background: #fff5f5; }');
    LSb.AppendLine('  .problem-low-confidence { border-left-color: #ffc107; background: #fffdf5; }');
    LSb.AppendLine('  .problem-no-evidence { border-left-color: #17a2b8; background: #f5fdff; }');
    LSb.AppendLine('  .problem-unreviewed { border-left-color: #6c757d; background: #f8f9fa; }');
    LSb.AppendLine('  .problem-uncertain { border-left-color: #dc3545; background: #fff5f5; }');
    LSb.AppendLine('  .problem-orphan { border-left-color: #e83e8c; background: #fdf5ff; }');
    LSb.AppendLine('  .problem-tree { color: #6c757d; font-size: 0.85em; }');
    LSb.AppendLine('  .problem code { font-size: 0.85em; color: #495057; }');
    LSb.AppendLine('  .badge-prob-no-evidence { background: #d1ecf1; color: #0c5460; }');
    LSb.AppendLine('  .badge-prob-unreviewed { background: #e2e3e5; color: #383d41; }');
    LSb.AppendLine('  .badge-prob-orphan { background: #f5d0e8; color: #8b4572; }');
    LSb.AppendLine('  .prob-section { margin-top: 1.5em; }');
    LSb.AppendLine('  .prob-summary { display: inline-block; margin: 0.5em 1em 0.5em 0;' +
      ' padding: 0.5em 1em; background: #f0f4f8; border-left: 3px solid #4a90e2; }');
    LSb.AppendLine('  .prob-summary strong { display: block; font-size: 1.5em; color: #4a90e2; }');
    LSb.AppendLine('</style>');

    LSb.AppendLine('<h1>Problems</h1>');
    LSb.AppendLine('<p><a href="index.html">'#$2190' Back to index</a></p>');

    // Summary
    LSb.AppendLine('<h2>Summary</h2>');
    var LFC: Integer := 0; if AFuncNodes <> nil then LFC := AFuncNodes.Count;
    var LMC: Integer := 0; if AModuleNodes <> nil then LMC := AModuleNodes.Count;
    var LVC: Integer := 0; if AViewNodes <> nil then LVC := AViewNodes.Count;
    var LDC: Integer := 0; if ADataNodes <> nil then LDC := ADataNodes.Count;
    LSb.AppendLine('<div class="prob-summary"><strong>' + LFC.ToString +
      '</strong>Function nodes</div>');
    LSb.AppendLine('<div class="prob-summary"><strong>' + LMC.ToString +
      '</strong>Module nodes</div>');
    LSb.AppendLine('<div class="prob-summary"><strong>' + LVC.ToString +
      '</strong>View nodes</div>');
    LSb.AppendLine('<div class="prob-summary"><strong>' + LDC.ToString +
      '</strong>Data nodes</div>');

    // Problem list
    LSb.AppendLine('<h2>Issues</h2>');
    LSb.AppendLine('<ul style="padding-left: 0;">');
    ScanNodes('Function', AFuncNodes);
    ScanNodes('Module', AModuleNodes);
    ScanNodes('View', AViewNodes);
    ScanNodes('Data', ADataNodes);
    LSb.AppendLine('</ul>');

    // Cross-tree consistency: detect broken cross-tree references
    LSb.AppendLine('<h2>Cross-Tree Consistency</h2>');
    LAllIds := TDictionary<string, Boolean>.Create;
    try
      if AFuncNodes <> nil then for var LN in AFuncNodes do LAllIds.AddOrSetValue(LN.Id, True);
      if AModuleNodes <> nil then for var LN in AModuleNodes do LAllIds.AddOrSetValue(LN.Id, True);
      if AViewNodes <> nil then for var LN in AViewNodes do LAllIds.AddOrSetValue(LN.Id, True);
      if ADataNodes <> nil then for var LN in ADataNodes do LAllIds.AddOrSetValue(LN.Id, True);

      LSb.AppendLine('<ul style="padding-left: 0;">');
      CheckNodeRefs('Function', AFuncNodes);
      CheckNodeRefs('Module', AModuleNodes);
      CheckNodeRefs('View', AViewNodes);
      CheckNodeRefs('Data', ADataNodes);
      LSb.AppendLine('</ul>');
    finally
      LAllIds.Free;
      LAllIds := nil;
    end;

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'problems.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
  end;
end;

procedure TDeepSpecRenderService.RenderBundlesPage(
  ABundles: TList<TSemanticBundle>;
  AFuncNodes, AModuleNodes, AViewNodes, ADataNodes: TList<TSpecNode>);
var
  LSb: TStringBuilder;
  LAllNodes: TDictionary<string, TSpecNode>;
begin
  LAllNodes := TDictionary<string, TSpecNode>.Create;
  LSb := TStringBuilder.Create;
  try
    // Build node lookup
    if AFuncNodes <> nil then for var N in AFuncNodes do LAllNodes.AddOrSetValue(N.Id, N);
    if AModuleNodes <> nil then for var N in AModuleNodes do LAllNodes.AddOrSetValue(N.Id, N);
    if AViewNodes <> nil then for var N in AViewNodes do LAllNodes.AddOrSetValue(N.Id, N);
    if ADataNodes <> nil then for var N in ADataNodes do LAllNodes.AddOrSetValue(N.Id, N);

    LSb.Append(PageHeader('Semantic Bundles'));

    LSb.AppendLine('<style>');
    LSb.AppendLine('  .bundle { margin: 1em 0; padding: 0.8em; border: 1px solid #dee2e6; border-radius: 6px; }');
    LSb.AppendLine('  .bundle-title { font-size: 1.1em; font-weight: 600; margin-bottom: 0.3em; }');
    LSb.AppendLine('  .bundle-desc { color: #6c757d; font-size: 0.9em; margin-bottom: 0.5em; }');
    LSb.AppendLine('  .bundle-nodes { list-style: none; padding-left: 0; }');
    LSb.AppendLine('  .bundle-node { padding: 0.3em 0.5em; margin: 0.2em 0; border-radius: 3px; background: #f8f9fa; }');
    LSb.AppendLine('  .bundle-actions { margin-top: 0.5em; }');
    LSb.AppendLine('  .bundle-actions button { margin-right: 0.5em; padding: 0.3em 0.8em; cursor: pointer; }');
    LSb.AppendLine('  .btn-accept-all { background: #d4edda; border-color: #c3e6cb; color: #155724; }');
    LSb.AppendLine('  .btn-reject-all { background: #f8d7da; border-color: #f5c6cb; color: #721c24; }');
    LSb.AppendLine('</style>');

    LSb.AppendLine('<h1>Semantic Bundles</h1>');
    LSb.AppendLine('<p><a href="index.html">'#$2190' Back to index</a></p>');

    if (ABundles = nil) or (ABundles.Count = 0) then
      LSb.AppendLine('<p><em>No bundles defined. Bundles group related nodes for batch review.</em></p>')
    else
    begin
      for var I := 0 to ABundles.Count - 1 do
      begin
        var LB := ABundles[I];
        LSb.AppendLine('<div class="bundle">');
        LSb.AppendLine('<div class="bundle-title">' + HtmlEscape(LB.Title) + '</div>');
        if LB.Description <> '' then
          LSb.AppendLine('<div class="bundle-desc">' + HtmlEscape(LB.Description) + '</div>');
        LSb.AppendLine('<ul class="bundle-nodes">');

        for var NId in LB.NodeIds do
        begin
          var LNode: TSpecNode;
          if LAllNodes.TryGetValue(NId, LNode) then
            LSb.AppendLine('<li class="bundle-node">' +
              StatusBadge(DeepSpec.Models.TSpecEnums.NodeStatusToStr(LNode.Status)) + ' ' +
              ConfidenceBadge(DeepSpec.Models.TSpecEnums.ConfidenceToStr(LNode.Confidence)) + ' ' +
              HtmlEscape(LNode.Title) +
              ' <code>' + HtmlEscape(NId) + '</code></li>')
          else
            LSb.AppendLine('<li class="bundle-node" style="color:#dc3545;">' +
              HtmlEscape(NId) + ' (not found)</li>');
        end;

        LSb.AppendLine('</ul>');
        LSb.AppendLine('<div class="bundle-actions">');
        LSb.AppendLine('<button class="btn-accept-all" data-action="bundle-accept" data-bundle-id="' +
          HtmlEscape(LB.Id) + '">Accept All</button>');
        LSb.AppendLine('<button class="btn-reject-all" data-action="bundle-reject" data-bundle-id="' +
          HtmlEscape(LB.Id) + '">Reject All</button>');
        LSb.AppendLine('</div>');
        LSb.AppendLine('</div>');
      end;
    end;

    // JS Bridge for bundle actions
    LSb.AppendLine('<script>');
    LSb.AppendLine('(function() {');
    LSb.AppendLine('  var hasBridge = !!(window.chrome && window.chrome.webview && window.chrome.webview.postMessage);');
    LSb.AppendLine('  document.addEventListener("click", function(e) {');
    LSb.AppendLine('    var t = e.target;');
    LSb.AppendLine('    if (!(t instanceof HTMLElement)) return;');
    LSb.AppendLine('    var action = t.getAttribute("data-action");');
    LSb.AppendLine('    if (!action) return;');
    LSb.AppendLine('    var bundleId = t.getAttribute("data-bundle-id") || "";');
    LSb.AppendLine('    var msg = {');
    LSb.AppendLine('      action: action,');
    LSb.AppendLine('      bundle_id: bundleId');
    LSb.AppendLine('    };');
    LSb.AppendLine('    if (hasBridge) {');
    LSb.AppendLine('      try { window.chrome.webview.postMessage(JSON.stringify(msg)); }');
    LSb.AppendLine('      catch (err) { console.error("DeepSpec bridge:", err); return; }');
    LSb.AppendLine('      t.textContent = "posted"; t.disabled = true;');
    LSb.AppendLine('    } else {');
    LSb.AppendLine('      alert("DeepSpec bridge unavailable.");');
    LSb.AppendLine('    }');
    LSb.AppendLine('  });');
    LSb.AppendLine('})();');
    LSb.AppendLine('</script>');

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'bundles.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
    LAllNodes.Free;
  end;
end;

end.
