{ ============================================================================
  DeepSpec.Services.Render

  HTML rendering service. Generates static HTML from .deepspec data
  for human review in WebView2 (P2) or external browser (P1).
  ============================================================================ }

unit DeepSpec.Services.Render;

interface

uses
  System.SysUtils,
  System.Classes,
  System.Generics.Collections,
  DeepSpec.Services.Scan,
  DeepSpec.Models;

type
  TDeepSpecRenderService = class(TInterfacedObject)
  private
    FBasePath: string;
    function HtmlEscape(const S: string): string;
    function PageHeader(const ATitle: string): string;
    function PageFooter: string;
    function StatusBadge(const AStatus: string): string;
    function ConfidenceBadge(const AConf: string): string;
    function SourceLayerBadge(const ALayer: string): string;
  public
    procedure Initialize(const ADeepSpecPath: string);
    procedure RenderScanReport(AScan: TDeepSpecScanService;
      const AProjectName, AProjectType: string);
    procedure RenderIndex(const AProjectName: string; ATotalFiles: Integer);
    procedure RenderTree(const ATreeName, ATreeTitle: string;
      ANodes: System.Generics.Collections.TList<DeepSpec.Models.TSpecNode>);
  end;

implementation

uses
  System.IOUtils,
  System.DateUtils;

procedure TDeepSpecRenderService.Initialize(const ADeepSpecPath: string);
begin
  FBasePath := TPath.Combine(ADeepSpecPath, 'html');
  if not TDirectory.Exists(FBasePath) then
    TDirectory.CreateDirectory(FBasePath);
end;

function TDeepSpecRenderService.HtmlEscape(const S: string): string;
begin
  Result := S
    .Replace('&', '&amp;')
    .Replace('<', '&lt;')
    .Replace('>', '&gt;')
    .Replace('"', '&quot;');
end;

function TDeepSpecRenderService.PageHeader(const ATitle: string): string;
begin
  Result :=
    '<!DOCTYPE html>' + sLineBreak +
    '<html lang="en">' + sLineBreak +
    '<head>' + sLineBreak +
    '  <meta charset="UTF-8">' + sLineBreak +
    '  <title>' + HtmlEscape(ATitle) + ' - DeepSpec</title>' + sLineBreak +
    '  <style>' + sLineBreak +
    '    body { font-family: -apple-system, "Segoe UI", sans-serif; margin: 2em; color: #333; }' + sLineBreak +
    '    h1 { border-bottom: 2px solid #4a90e2; padding-bottom: 0.5em; }' + sLineBreak +
    '    h2 { color: #4a90e2; margin-top: 1.5em; }' + sLineBreak +
    '    .stat { display: inline-block; margin: 0.5em 1em 0.5em 0; padding: 0.5em 1em;' + sLineBreak +
    '            background: #f0f4f8; border-left: 3px solid #4a90e2; }' + sLineBreak +
    '    .stat strong { display: block; font-size: 1.5em; color: #4a90e2; }' + sLineBreak +
    '    .file-list { background: #f9f9f9; padding: 1em; border-radius: 4px; max-height: 400px; overflow-y: auto; }' + sLineBreak +
    '    .file-list code { display: block; padding: 0.2em 0; font-size: 0.9em; }' + sLineBreak +
    '    .badge { display: inline-block; padding: 0.2em 0.6em; border-radius: 3px;' + sLineBreak +
    '             font-size: 0.85em; margin-right: 0.5em; }' + sLineBreak +
    '    .badge-doc { background: #e3f2fd; color: #1976d2; }' + sLineBreak +
    '    .badge-code { background: #f3e5f5; color: #7b1fa2; }' + sLineBreak +
    '    .badge-ui { background: #fff3e0; color: #f57c00; }' + sLineBreak +
    '    .badge-config { background: #e8f5e9; color: #388e3c; }' + sLineBreak +
    '    .badge-ai { background: #fce4ec; color: #c2185b; }' + sLineBreak +
    '    footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #eee;' + sLineBreak +
    '             color: #999; font-size: 0.85em; }' + sLineBreak +
    '  </style>' + sLineBreak +
    '</head>' + sLineBreak +
    '<body>' + sLineBreak;
end;

function TDeepSpecRenderService.PageFooter: string;
begin
  Result :=
    '<footer>' + sLineBreak +
    '  Generated by DeepSpec at ' +
    HtmlEscape(FormatDateTime('yyyy-mm-dd hh:nn:ss', Now)) + sLineBreak +
    '</footer>' + sLineBreak +
    '</body>' + sLineBreak +
    '</html>' + sLineBreak;
end;

procedure TDeepSpecRenderService.RenderScanReport(AScan: TDeepSpecScanService;
  const AProjectName, AProjectType: string);
var
  LSb: TStringBuilder;

  procedure AppendCategory(const ATitle, ABadgeClass: string;
    AFiles: TArray<string>);
  begin
    LSb.AppendLine('<h2><span class="badge ' + ABadgeClass + '">' +
      HtmlEscape(ATitle) + '</span> ' + Length(AFiles).ToString + '</h2>');
    if Length(AFiles) = 0 then
      LSb.AppendLine('<p><em>No files in this category.</em></p>')
    else
    begin
      LSb.AppendLine('<div class="file-list">');
      for var LFile in AFiles do
        LSb.AppendLine('<code>' + HtmlEscape(LFile) + '</code>');
      LSb.AppendLine('</div>');
    end;
  end;

begin
  LSb := TStringBuilder.Create;
  try
    LSb.Append(PageHeader('Scan Report'));

    LSb.AppendLine('<h1>Scan Report: ' + HtmlEscape(AProjectName) + '</h1>');
    LSb.AppendLine('<p>Project type: <strong>' + HtmlEscape(AProjectType) + '</strong></p>');

    LSb.AppendLine('<h2>Summary</h2>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.TotalFiles.ToString + '</strong>Total files</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcDocuments).ToString + '</strong>Documents</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcCode).ToString + '</strong>Code</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcUI).ToString + '</strong>UI</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcConfig).ToString + '</strong>Config</div>');
    LSb.AppendLine('<div class="stat"><strong>' + AScan.CategoryCount(fcAiRules).ToString + '</strong>AI Rules</div>');

    AppendCategory('Documents', 'badge-doc', AScan.GetFilesByCategory(fcDocuments));
    AppendCategory('Code', 'badge-code', AScan.GetFilesByCategory(fcCode));
    AppendCategory('UI', 'badge-ui', AScan.GetFilesByCategory(fcUI));
    AppendCategory('Config', 'badge-config', AScan.GetFilesByCategory(fcConfig));
    AppendCategory('AI Rules', 'badge-ai', AScan.GetFilesByCategory(fcAiRules));

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'scan-report.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
  end;
end;

procedure TDeepSpecRenderService.RenderIndex(const AProjectName: string;
  ATotalFiles: Integer);
var
  LSb: TStringBuilder;
begin
  LSb := TStringBuilder.Create;
  try
    LSb.Append(PageHeader('Index'));
    LSb.AppendLine('<h1>DeepSpec: ' + HtmlEscape(AProjectName) + '</h1>');
    LSb.AppendLine('<p>Welcome to your project specification.</p>');
    LSb.AppendLine('<h2>Pages</h2>');
    LSb.AppendLine('<ul>');
    LSb.AppendLine('  <li><a href="scan-report.html">Scan Report</a> (' +
      ATotalFiles.ToString + ' files)</li>');
    LSb.AppendLine('  <li><a href="function-tree.html">Function Tree</a></li>');
    LSb.AppendLine('  <li><a href="module-tree.html">Module Tree</a></li>');
    LSb.AppendLine('  <li><a href="view-tree.html">View Tree</a></li>');
    LSb.AppendLine('</ul>');
    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, 'index.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
  end;
end;

function TDeepSpecRenderService.StatusBadge(const AStatus: string): string;
begin
  Result := '<span class="badge badge-' + AStatus + '">' +
    HtmlEscape(AStatus) + '</span>';
end;

function TDeepSpecRenderService.ConfidenceBadge(const AConf: string): string;
begin
  Result := '<span class="badge badge-conf-' + AConf + '">' +
    HtmlEscape(AConf) + '</span>';
end;

function TDeepSpecRenderService.SourceLayerBadge(const ALayer: string): string;
begin
  Result := '<span class="badge badge-source">' + HtmlEscape(ALayer) + '</span>';
end;

procedure TDeepSpecRenderService.RenderTree(const ATreeName, ATreeTitle: string;
  ANodes: System.Generics.Collections.TList<DeepSpec.Models.TSpecNode>);
var
  LSb: TStringBuilder;
  LNodeMap: TDictionary<string, DeepSpec.Models.TSpecNode>;

  procedure RenderNode(const ANodeId: string; ADepth: Integer);
  begin
    var LNode: DeepSpec.Models.TSpecNode;
    if not LNodeMap.TryGetValue(ANodeId, LNode) then Exit;

    var LStatus := DeepSpec.Models.TSpecEnums.NodeStatusToStr(LNode.Status);

    LSb.AppendLine('<li class="node node-depth-' + ADepth.ToString + '" data-node-id="' +
      HtmlEscape(LNode.Id) + '">');
    LSb.Append('<div class="node-header">');
    LSb.Append('<span class="node-title">' + HtmlEscape(LNode.Title) + '</span> ');
    LSb.Append('<span class="node-kind">' + HtmlEscape(LNode.Kind) + '</span> ');
    LSb.Append(StatusBadge(LStatus));
    LSb.Append(' ');
    LSb.Append(ConfidenceBadge(DeepSpec.Models.TSpecEnums.ConfidenceToStr(LNode.Confidence)));
    LSb.Append(' ');
    LSb.Append(SourceLayerBadge(DeepSpec.Models.TSpecEnums.SourceLayerToStr(LNode.SourceLayer)));

    // Decision buttons for candidate nodes (JS Bridge writes back via WebView2 postMessage)
    if LStatus = 'candidate' then
    begin
      LSb.Append(' <span class="decision-toolbar">');
      LSb.Append('<button class="btn-confirm" data-action="node-confirm" data-node-id="' +
        HtmlEscape(LNode.Id) + '" data-node-title="' + HtmlEscape(LNode.Title) +
        '" title="Confirm this node">'#$2713' Confirm</button>');
      LSb.Append('<button class="btn-reject" data-action="node-reject" data-node-id="' +
        HtmlEscape(LNode.Id) + '" data-node-title="' + HtmlEscape(LNode.Title) +
        '" title="Reject this node">'#$2715' Reject</button>');
      LSb.Append('</span>');
    end;

    LSb.AppendLine('</div>');

    if LNode.Summary <> '' then
      LSb.AppendLine('<div class="node-summary">' + HtmlEscape(LNode.Summary) + '</div>');

    if Length(LNode.AcceptanceCriteria) > 0 then
    begin
      LSb.AppendLine('<details class="node-criteria"><summary>Acceptance Criteria</summary><ul>');
      for var LCrit in LNode.AcceptanceCriteria do
        LSb.AppendLine('<li>' + HtmlEscape(LCrit) + '</li>');
      LSb.AppendLine('</ul></details>');
    end;

    if Length(LNode.Children) > 0 then
    begin
      LSb.AppendLine('<ul class="node-children">');
      for var LChildId in LNode.Children do
        RenderNode(LChildId, ADepth + 1);
      LSb.AppendLine('</ul>');
    end;

    LSb.AppendLine('</li>');
  end;

begin
  LSb := TStringBuilder.Create;
  LNodeMap := TDictionary<string, DeepSpec.Models.TSpecNode>.Create;
  try
    for var LNode in ANodes do
      LNodeMap.AddOrSetValue(LNode.Id, LNode);

    LSb.Append(PageHeader(ATreeTitle));

    // Tree-specific styles
    LSb.AppendLine('<style>');
    LSb.AppendLine('  .node { list-style: none; margin: 0.5em 0; }');
    LSb.AppendLine('  .node-header { padding: 0.4em; border-radius: 4px;');
    LSb.AppendLine('                 background: #f8f9fa; cursor: pointer; }');
    LSb.AppendLine('  .node-header:hover { background: #e9ecef; }');
    LSb.AppendLine('  .node-title { font-weight: 600; }');
    LSb.AppendLine('  .node-kind { color: #6c757d; font-size: 0.9em; font-style: italic; }');
    LSb.AppendLine('  .node-summary { padding: 0.3em 0.4em; color: #495057; font-size: 0.95em; }');
    LSb.AppendLine('  .node-children { padding-left: 1.5em; border-left: 2px solid #dee2e6; }');
    LSb.AppendLine('  .badge-candidate { background: #fff3cd; color: #856404; }');
    LSb.AppendLine('  .badge-confirmed { background: #d4edda; color: #155724; }');
    LSb.AppendLine('  .badge-uncertain { background: #f8d7da; color: #721c24; }');
    LSb.AppendLine('  .badge-rejected { background: #d6d8db; color: #383d41; }');
    LSb.AppendLine('  .badge-superseded { background: #d6d8db; color: #383d41; }');
    LSb.AppendLine('  .badge-conf-low { background: #f8d7da; color: #721c24; }');
    LSb.AppendLine('  .badge-conf-medium { background: #fff3cd; color: #856404; }');
    LSb.AppendLine('  .badge-conf-high { background: #d4edda; color: #155724; }');
    LSb.AppendLine('  .badge-source { background: #cce5ff; color: #004085; font-size: 0.8em; }');
    LSb.AppendLine('  details summary { cursor: pointer; color: #4a90e2; padding: 0.3em 0.4em; }');
    LSb.AppendLine('  .decision-toolbar { margin-left: 0.5em; }');
    LSb.AppendLine('  .decision-toolbar button { font-size: 0.8em; margin-left: 0.25em;');
    LSb.AppendLine('    padding: 0.15em 0.5em; border: 1px solid #ced4da; border-radius: 3px;');
    LSb.AppendLine('    background: #fff; cursor: pointer; }');
    LSb.AppendLine('  .decision-toolbar .btn-confirm { color: #155724; border-color: #c3e6cb; }');
    LSb.AppendLine('  .decision-toolbar .btn-confirm:hover { background: #d4edda; }');
    LSb.AppendLine('  .decision-toolbar .btn-reject { color: #721c24; border-color: #f5c6cb; }');
    LSb.AppendLine('  .decision-toolbar .btn-reject:hover { background: #f8d7da; }');
    LSb.AppendLine('  .decision-toolbar button.posted { opacity: 0.5; cursor: default; }');
    LSb.AppendLine('</style>');

    LSb.AppendLine('<h1>' + HtmlEscape(ATreeTitle) + '</h1>');
    LSb.AppendLine('<p><a href="index.html">'#$2190' Back to index</a></p>');

    if ANodes.Count = 0 then
      LSb.AppendLine('<p><em>This tree is empty. Run LLM generation to populate.</em></p>')
    else
    begin
      LSb.AppendLine('<ul class="tree-root" style="padding-left: 0;">');
      // Render roots first (no parent_id)
      for var LRoot in ANodes do
        if LRoot.ParentId = '' then
          RenderNode(LRoot.Id, 0);
      LSb.AppendLine('</ul>');
    end;

    // JS Bridge: forward decision-button clicks to the WebView2 host.
    // Falls back to a no-op (with visible warning) when opened in a regular browser.
    LSb.AppendLine('<script>');
    LSb.AppendLine('(function() {');
    LSb.AppendLine('  var hasBridge = !!(window.chrome && window.chrome.webview && window.chrome.webview.postMessage);');
    LSb.AppendLine('  document.addEventListener("click", function(e) {');
    LSb.AppendLine('    var t = e.target;');
    LSb.AppendLine('    if (!(t instanceof HTMLElement)) return;');
    LSb.AppendLine('    var action = t.getAttribute("data-action");');
    LSb.AppendLine('    if (!action) return;');
    LSb.AppendLine('    if (t.classList.contains("posted")) return;');
    LSb.AppendLine('    var msg = {');
    LSb.AppendLine('      action: action,');
    LSb.AppendLine('      node_id: t.getAttribute("data-node-id") || "",');
    LSb.AppendLine('      node_title: t.getAttribute("data-node-title") || ""');
    LSb.AppendLine('    };');
    LSb.AppendLine('    if (hasBridge) {');
    LSb.AppendLine('      try { window.chrome.webview.postMessage(JSON.stringify(msg)); }');
    LSb.AppendLine('      catch (err) { console.error("DeepSpec bridge:", err); return; }');
    LSb.AppendLine('      t.classList.add("posted");');
    LSb.AppendLine('      t.textContent = (action === "node-confirm" ? "'#$2713' posted" : "'#$2715' posted");');
    LSb.AppendLine('    } else {');
    LSb.AppendLine('      alert("DeepSpec bridge unavailable. Open this page inside DeepSpec to record decisions.");');
    LSb.AppendLine('    }');
    LSb.AppendLine('  });');
    LSb.AppendLine('})();');
    LSb.AppendLine('</script>');

    LSb.Append(PageFooter);

    TFile.WriteAllText(TPath.Combine(FBasePath, ATreeName + '.html'),
      LSb.ToString, TEncoding.UTF8);
  finally
    LSb.Free;
    LNodeMap.Free;
  end;
end;

end.
