-- Applied by tools/migrate_chapter_coherence.py.
-- SQLite ADD COLUMN has no portable IF NOT EXISTS; the Python migration probes
-- PRAGMA table_info before adding writing_chapter_reviews.chapter_coherence.
--
-- Adds:
--   writing_chapter_reviews.chapter_coherence INTEGER NULL CHECK (0..100)
--
-- Existing review rows remain NULL: legacy seven-dimension reviews must not be
-- assigned a fabricated coherence score. New reviews always write all eight
-- dimensions through ChapterReviewOrchestrator.
