-- 迁移：补 writing_projects.suspense_decay_floor 列（章级悬疑张力衰减回炉线）
-- 日期：2026-07-09
-- 目的：
--   任务#21「suspense 衰减监控回炉」在 schema.sql 给 writing_projects 加了
--   suspense_decay_floor INTEGER NOT NULL DEFAULT 82（CHECK >= 82），章末 review
--   orchestrator _chapter_suspense_decay_floor 据此判断「本章 winner 行
--   suspense_tension_median 中位数 < 回炉线则强制回炉（E13）」。
--   但既有生产库（如《白灯法则》inkflow.db）是用加列前的旧 schema.sql 建的，
--   缺该列 → SELECT suspense_decay_floor 抛 OperationalError → review 全崩。
--
-- 幂等说明：
--   SQLite 的 ALTER TABLE ADD COLUMN 不支持 IF NOT EXISTS。纯 SQL 无法在「列已存在」
--   时优雅跳过（重复 ADD 会报 duplicate column）。故本文件不直接 executescript，
--   真正幂等执行见 tools/migrate_suspense_decay_floor.py（PRAGMA 探测后条件 ALTER）。
--   既有库执行：python tools/migrate_suspense_decay_floor.py --db <db>
--   新建库（CLI init 读新 schema.sql）已含此列，无需本迁移。
--
-- 手动一次性执行（确认列缺失时）：取消下行注释后 sqlite3 ".read" 本文件。
-- ALTER TABLE writing_projects ADD COLUMN suspense_decay_floor INTEGER NOT NULL DEFAULT 82;
