/**
 * DeepFrames Remotion Composition — renders Video IR scenes.
 *
 * This is a skeleton composition that reads SceneInputProps
 * and renders each scene as a <Sequence> with background + subtitle.
 *
 * In production: scenes are loaded from the Video IR JSON file,
 * background images are pre-generated by the DeepFrames image pipeline,
 * and audio is mixed in via the audio_manifest binding.
 */

import React from 'react';
import { Composition, Sequence, useCurrentFrame, useVideoConfig } from 'remotion';
import type { VideoIRScene } from './VideoIR';

interface SceneInputProps {
  scenes: VideoIRScene[];
  width: number;
  height: number;
  fps: number;
}

const SceneRenderer: React.FC<{ scene: VideoIRScene }> = ({ scene }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const totalFrames = Math.round(scene.duration_sec * fps);
  const progress = frame / totalFrames;

  // Fade in/out opacity
  const fadeInFrames = scene.transitions.in === 'fade' ? Math.round(fps * 0.5) : 0;
  const fadeOutFrames = scene.transitions.out === 'fade' ? Math.round(fps * 0.5) : 0;

  let opacity = 1;
  if (frame < fadeInFrames) {
    opacity = frame / fadeInFrames;
  } else if (frame > totalFrames - fadeOutFrames) {
    opacity = (totalFrames - frame) / fadeOutFrames;
  }

  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        alignItems: 'center',
        opacity,
        background: 'linear-gradient(180deg, #1a1a2e 0%, #16213e 100%)',
        position: 'relative',
      }}
    >
      {/* Background placeholder */}
      <div
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          color: 'rgba(255,255,255,0.15)',
          fontSize: 48,
          fontFamily: 'sans-serif',
        }}
      >
        {scene.layers.background.prompt}
      </div>

      {/* Subtitle */}
      {scene.layers.subtitle && (
        <div
          style={{
            padding: '40px 60px',
            marginBottom: '10%',
            background: 'rgba(0,0,0,0.6)',
            borderRadius: 8,
            maxWidth: '80%',
          }}
        >
          <p
            style={{
              color: '#ffffff',
              fontSize: 36,
              fontFamily: 'sans-serif',
              textAlign: 'center',
              textShadow: '2px 2px 4px rgba(0,0,0,0.8)',
              margin: 0,
              lineHeight: 1.5,
            }}
          >
            {scene.layers.subtitle.text}
          </p>
        </div>
      )}
    </div>
  );
};

export const DeepFramesComposition: React.FC<SceneInputProps> = ({
  scenes,
  width,
  height,
  fps,
}) => {
  let offsetFrames = 0;

  return (
    <Composition
      id="DeepFramesVideo"
      component={() => (
        <>
          {scenes.map((scene, index) => {
            const startFrame = offsetFrames;
            const durationFrames = Math.round(scene.duration_sec * fps);
            offsetFrames += durationFrames;

            return (
              <Sequence
                key={scene.scene_id || `scene_${index}`}
                from={startFrame}
                durationInFrames={durationFrames}
              >
                <SceneRenderer scene={scene} />
              </Sequence>
            );
          })}
        </>
      )}
      width={width}
      height={height}
      fps={fps}
      durationInFrames={Math.round(
        scenes.reduce((sum, s) => sum + s.duration_sec, 0) * fps
      )}
      defaultProps={{ scenes, width, height, fps }}
    />
  );
};