apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uniflow
resources:
  - uniflow-deployment.yaml
  - uniflow-worker.yaml
commonLabels:
  app.kubernetes.io/name: uniflow
  app.kubernetes.io/part-of: uniflow
